PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `Names` (
	`ID`	INT NOT NULL PRIMARY KEY,
	`Category` TEXT NOT NULL,
	`Name`	TEXT NOT NULL
);
CREATE TABLE `Resources` (
	`ID`	INT NOT NULL PRIMARY KEY,
	`TypeID`	INT NOT NULL,
	`Path`	TEXT,
	FOREIGN KEY(`TypeID`) REFERENCES `Names`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `ResourceDependencies` (
	`SourceID`	INT NOT NULL,
	`TargetID`	INT NOT NULL,
	FOREIGN KEY(`SourceID`) REFERENCES `Resources`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(`TargetID`) REFERENCES `Resources`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `Entities` (
	`ID`	INT NOT NULL PRIMARY KEY,
	`GroupID`	INT NOT NULL,
	`Name`	TEXT NOT NULL,
	FOREIGN KEY(`GroupID`) REFERENCES `EntityGroups`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `EntityGroups` (
	`ID`	INT NOT NULL PRIMARY KEY,
	`Name`	TEXT NOT NULL
);
INSERT INTO EntityGroups VALUES(0,'Root');
CREATE TABLE `EntityComponents` (
	`ID`	INT NOT NULL,
	`ComponentID`	INT NOT NULL,
	FOREIGN KEY(`ID`) REFERENCES `Entities`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(`ComponentID`) REFERENCES `Components`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `Components` (
	`ID`	INT NOT NULL PRIMARY KEY,
	`Type`	INT NOT NULL,
	FOREIGN KEY(`Type`) REFERENCES `Names`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `ModelComponents` (
	`ID`	INT NOT NULL PRIMARY KEY,
	`ResourceID` INT NOT NULL,
	`ViewDistance` FLOAT NOT NULL,
	FOREIGN KEY(`ID`) REFERENCES `Components`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(`ResourceID`) REFERENCES `Resources`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `ModelComponentMaterials` (
	`ID`	INT NOT NULL,
	`MeshGroupID` INT NOT NULL,
	`ResourceID` INT NOT NULL,
	FOREIGN KEY(`ID`) REFERENCES `Components`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(`ResourceID`) REFERENCES `Resources`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `CameraComponents` (
	`ID`	INT NOT NULL PRIMARY KEY,
	`FieldOfView`	FLOAT NOT NULL,
	'Near'		FLOAT NOT NULL,
	'Far'		FLOAT NOT NULL,
	'Aspect'	FLOAT NOT NULL,
	FOREIGN KEY(`ID`) REFERENCES `Components`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `TransformComponents` (
	`ID`	INT NOT NULL PRIMARY KEY,
	`X`		FLOAT NOT NULL,
	'Y'		FLOAT NOT NULL,
	'Z'		FLOAT NOT NULL,
	'Scale'	FLOAT NOT NULL,
	'Yaw'	FLOAT NOT NULL,
	'Pitch' FLOAT NOT NULL,
	'Roll'	FLOAT NOT NULL
);
CREATE TABLE `SpaceComponents` (
	`ID`	INT NOT NULL PRIMARY KEY,
	`GroupID`	INT NOT NULL,
	FOREIGN KEY(`GroupID`) REFERENCES `EntityGroups`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `EnvCubeComponents` (
	`ID`	INT NOT NULL PRIMARY KEY,
	`ResourceID`	INT NOT NULL,
	FOREIGN KEY(`ResourceID`) REFERENCES `Resources`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMIT;
