#pragma once

#include "CoreMinimal.h"
#include "Modules/ModuleManager.h"
#include "CoreUObject.h"
#include "Engine.h"
#include "UnrealEd.h"
#include "SlateBasics.h"
#include "Internationalization.h"
#include "ISceneExplorer.h"
#include "ILeavesExporter.h"
#include "LevelEditor.h"
#include "MultiBox.h"
#include "PropertyEditorModule.h"
#include "FLeavesCommands.h"
#include "Runtime/Landscape/Classes/LandscapeComponent.h"
#include "Runtime/Engine/Classes/Materials/MaterialExpressionTextureBase.h"
#include "Runtime/Engine/Classes/Engine/MapBuildDataRegistry.h"
#include <memory>
