/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/usr/local/lib/tcc"
#endif
#define GCC_MAJOR 4
#define GCC_MINOR 9
#if defined(__x86_64__) || defined(__amd64) || defined (_WIN64)
#define HOST_X86_64 1
#else
#define HOST_X86_64 0
#endif
#define TCC_VERSION "0.9.26"

#ifdef _WIN32
#define TCC_TARGET_PE
#else
// #define TCC_TARGET_COFF
#endif

#define COMPILE_I386
// #define COMPILE_IL
// #define COMPILE_ARM
// #define COMPILE_C67
